LTO-ENABLE = yes

COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

MUSIC_ENABLE = no

KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = no

VPATH += keyboards/gboards/
COMBO_ENABLE = yes

REPEAT_KEY_ENABLE = no
VIA_ENABLE = no

TAP_DANCE_ENABLE = no

